DATA: Medicare data displaying the 2016 use of Medicare and Medicare savings across the US.

In [514]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as pyplot
import seaborn as sns

df = pd.read_csv('Medicare ACA state data 12_2016.csv')
print(df.info)

<bound method DataFrame.info of     index                 State  Medicare Enrollment (Sept. 2016)  \
0       0              Alabama                           989855.0
1       1               Alaska                            88966.0
2       2              Arizona                          1175624.0
3       3             Arkansas                           606146.0
4       4            California                         5829777.0
5       5              Colorado                          820234.0
6       6           Connecticut                          644136.0
7       7             Delaware                           186835.0
8       8  District of Columbia                           90492.0
9       9              Florida                          4149593.0
10     10              Georgia                          1574058.0
11     11                Hawaii                          252514.0
12     12                 Idaho                          294284.0
13     13             Illinois                          2118300.0
14     14              Indiana                          1181014.0
15     15                 Iowa                           587780.0
16     16               Kansas                           499753.0
17     17              Kentucky                          881938.0
18     18            Louisiana                           817272.0
19     19                Maine                           315160.0
20     20              Maryland                          960848.0
21     21         Massachusetts                         1252277.0
22     22             Michigan                          1947787.0
23     23             Minnesota                          944222.0
24     24          Mississippi                           571699.0
25     25             Missouri                          1163543.0
26     26              Montana                           209389.0
27     27             Nebraska                           322796.0
28     28                Nevada                          471747.0
29     29        New Hampshire                           275803.0
30     30           New Jersey                          1528961.0
31     31            New Mexico                          385918.0
32     32              New York                         3424666.0
33     33       North Carolina                          1823454.0
34     34         North Dakota                           122294.0
35     35                 Ohio                          2208504.0
36     36             Oklahoma                           693677.0
37     37                Oregon                          784032.0
38     38         Pennsylvania                          2588577.0
39     39          Rhode Island                          208324.0
40     40       South Carolina                           974114.0
41     41         South Dakota                           161464.0
42     42            Tennessee                          1266920.0
43     43                Texas                          3765946.0
44     44                 Utah                           358887.0
45     45               Vermont                          136021.0
46     46             Virginia                          1392261.0
47     47            Washington                         1238649.0
48     48        West Virginia                           423500.0
49     49            Wisconsin                          1084854.0
50     50               Wyoming                           99128.0
51     51                   NaN                               NaN
52     52                   NaN                               NaN
53     53                   NaN                               NaN

    Medicare Beneficiaries benefitting from donut hole savings (2015)  \
0                                             90556.0
1                                              3094.0
2                                             96954.0
3                                             40658.0
4                                            419078.0
5                                             59459.0
6                                             66843.0
7                                             24223.0
8                                              3258.0
9                                            355360.0
10                                           141609.0
11                                            23762.0
12                                            19821.0
13                                           196727.0
14                                           123302.0
15                                            55670.0
16                                            46642.0
17                                            89343.0
18                                            73530.0
19                                            18970.0
20                                            86073.0
21                                            83303.0
22                                           212075.0
23                                            73484.0
24                                            41041.0
25                                           107008.0
26                                            13384.0
27                                            30366.0
28                                            34285.0
29                                            21026.0
30                                           211881.0
31                                            23642.0
32                                           359127.0
33                                           173412.0
34                                            11866.0
35                                           237303.0
36                                            65788.0
37                                            54007.0
38                                           297606.0
39                                            15785.0
40                                            98589.0
41                                            13616.0
42                                           114993.0
43                                           346750.0
44                                            28336.0
45                                            10955.0
46                                           114138.0
47                                            74902.0
48                                            45280.0
49                                            90303.0
50                                             8008.0
51                                                NaN
52                                                NaN
53                                                NaN

    Total Medicare beneficiary savings from donut hole (2015)  \
0                                          97330073.0
1                                           3184420.0
2                                          93694466.0
3                                          36436080.0
4                                         437630655.0
5                                          58449048.0
6                                          78487237.0
7                                          28586178.0
8                                           3496014.0
9                                         350888326.0
10                                        148784101.0
11                                         30027279.0
12                                         17584133.0
13                                        204732932.0
14                                        127674560.0
15                                         53282941.0
16                                         43407473.0
17                                         99034242.0
18                                         72702732.0
19                                         18712752.0
20                                         99702303.0
21                                         86517318.0
22                                        249358887.0
23                                         72072204.0
24                                         35832183.0
25                                        102895608.0
26                                         12097212.0
27                                         27674906.0
28                                         33160363.0
29                                         22023187.0
30                                        262865304.0
31                                         23792440.0
32                                        429276680.0
33                                        175662465.0
34                                         11470436.0
35                                        258550550.0
36                                         67925763.0
37                                         50494389.0
38                                        313453847.0
39                                         14392653.0
40                                        107311751.0
41                                         12395059.0
42                                        109733424.0
43                                        366381273.0
44                                         27106568.0
45                                         12077364.0
46                                        115809752.0
47                                         73272041.0
48                                         54194138.0
49                                         93517959.0
50                                          7634708.0
51                                                NaN
52                                                NaN
53                                                NaN

    Average per Medicare Beneficiary Donut Hole Savings (2015)  \
0                                              1075.0
1                                              1029.0
2                                               966.0
3                                               896.0
4                                              1044.0
5                                               983.0
6                                              1174.0
7                                              1180.0
8                                              1073.0
9                                               987.0
10                                             1051.0
11                                             1264.0
12                                              887.0
13                                             1041.0
14                                             1035.0
15                                              957.0
16                                              931.0
17                                             1108.0
18                                              989.0
19                                              986.0
20                                             1158.0
21                                             1039.0
22                                             1176.0
23                                              981.0
24                                              873.0
25                                              962.0
26                                              904.0
27                                              911.0
28                                              967.0
29                                             1047.0
30                                             1241.0
31                                             1006.0
32                                             1195.0
33                                             1013.0
34                                              967.0
35                                             1090.0
36                                             1032.0
37                                              935.0
38                                             1053.0
39                                              912.0
40                                             1088.0
41                                              910.0
42                                              954.0
43                                             1057.0
44                                              957.0
45                                             1102.0
46                                             1015.0
47                                              978.0
48                                             1197.0
49                                             1036.0
50                                              953.0
51                                                NaN
52                                                NaN
53                                                NaN

    Part B Beneficiaries Using Free Preventive Services (2015)  \
0                                            531567.0
1                                             46876.0
2                                            481230.0
3                                            337214.0
4                                           2202117.0
5                                            323128.0
6                                            344091.0
7                                            133283.0
8                                             46684.0
9                                           1826053.0
10                                           751478.0
11                                            79163.0
12                                           121236.0
13                                          1185594.0
14                                           637488.0
15                                           370648.0
16                                           299776.0
17                                           461771.0
18                                           387587.0
19                                           165892.0
20                                           604509.0
21                                           725251.0
22                                           949718.0
23                                           271698.0
24                                           345847.0
25                                           580049.0
26                                           106395.0
27                                           193448.0
28                                           187012.0
29                                           176282.0
30                                           940537.0
31                                           156682.0
32                                          1486645.0
33                                           950381.0
34                                            71547.0
35                                           885625.0
36                                           388681.0
37                                           269101.0
38                                          1081445.0
39                                            92065.0
40                                           549051.0
41                                            87816.0
42                                           600644.0
43                                          1746043.0
44                                           146179.0
45                                            87184.0
46                                           813642.0
47                                           543203.0
48                                           213916.0
49                                           481012.0
50                                            56898.0
51                                                NaN
52                                                NaN
53                                                NaN

    Share of Part B Beneficiaries Using Free Preventive Services (2015)  \
0                                               0.742
1                                               0.587
2                                               0.703
3                                               0.712
4                                               0.685
5                                               0.676
6                                               0.773
7                                               0.808
8                                               0.675
9                                               0.752
10                                              0.728
11                                              0.672
12                                              0.646
13                                              0.744
14                                              0.733
15                                              0.767
16                                              0.724
17                                              0.731
18                                              0.713
19                                              0.714
20                                              0.758
21                                              0.789
22                                              0.741
23                                              0.684
24                                              0.716
25                                              0.728
26                                              0.653
27                                              0.718
28                                              0.649
29                                              0.744
30                                              0.772
31                                              0.634
32                                              0.744
33                                              0.765
34                                              0.729
35                                              0.716
36                                              0.706
37                                              0.664
38                                              0.747
39                                              0.764
40                                              0.756
41                                              0.699
42                                              0.748
43                                              0.717
44                                              0.679
45                                              0.728
46                                              0.762
47                                              0.681
48                                              0.707
49                                              0.751
50                                              0.621
51                                                NaN
52                                                NaN
53                                                NaN

    % Change in Hospital Readmission Rates Among Medicare Beneficiaries (2010-2015)  \
0                                                -5.8
1                                                -5.5
2                                               -10.8
3                                                -6.2
4                                                -5.7
5                                                -9.2
6                                                -7.7
7                                               -10.3
8                                                -7.5
9                                                -2.7
10                                               -7.4
11                                              -13.4
12                                               -2.4
13                                              -12.1
14                                               -7.5
15                                               -6.5
16                                               -9.8
17                                               -9.1
18                                               -9.6
19                                               -3.7
20                                              -10.4
21                                               -5.8
22                                               -3.2
23                                               -7.0

In [515]:
import pandas as pd

df = pd.read_csv('Medicare ACA state data 12_2016.csv')
df.info()
print

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 13 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   index                                                                            54 non-null     int64
 1   State                                                                            51 non-null     object
 2   Medicare Enrollment (Sept. 2016)                                                 51 non-null     float64
 3   Medicare Beneficiaries benefitting from donut hole savings (2015)                51 non-null     float64
 4   Total Medicare beneficiary savings from donut hole (2015)                        51 non-null     float64
 5   Average per Medicare Beneficiary Donut Hole Savings (2015)                       51 non-null     float64
 6   Part B Beneficiaries Using Free Preventive Services (2015)                       51 non-null     float64
 7   Share of Part B Beneficiaries Using Free Preventive Services (2015)              51 non-null     float64
 8   % Change in Hospital Readmission Rates Among Medicare Beneficiaries (2010-2015)  51 non-null     float64
 9   Avoided Readmissions (2015)                                                      51 non-null     float64
 10  Number of Accountable Care Organizations (2016)                                  51 non-null     float64
 11  Unnamed: 10                                                                      0 non-null      float64
 12  Unnamed: 11                                                                      0 non-null      float64
dtypes: float64(11), int64(1), object(1)
memory usage: 5.6+ KB

In [516]:
import pandas as pd

df = pd.read_csv('Medicare ACA state data 12_2016.csv')
df.describe()

,index,Medicare Enrollment (Sept. 2016),Medicare Beneficiaries benefitting from donut hole savings (2015),Total Medicare beneficiary savings from donut hole (2015),Average per Medicare Beneficiary Donut Hole Savings (2015),Part B Beneficiaries Using Free Preventive Services (2015),Share of Part B Beneficiaries Using Free Preventive Services (2015),% Change in Hospital Readmission Rates Among Medicare Beneficiaries (2010-2015),Avoided Readmissions (2015),Number of Accountable Care Organizations (2016),Unnamed: 10,Unnamed: 11
count,54.000000,5.100000e+01,51.000000,5.100000e+01,51.000000,5.100000e+01,51.000000,51.000000,51.000000,51.000000,0.0,0.0
mean,26.500000,1.095961e+06,98964.529412,1.045643e+08,1026.764706,5.200271e+05,0.716765,-7.186275,1932.455490,13.431373,NaN,NaN
std,15.732133,1.147094e+06,103440.955454,1.126652e+08,95.129719,4.882053e+05,0.044987,3.043683,2054.483382,10.837444,NaN,NaN
min,0.000000,8.896600e+04,3094.000000,3.184420e+06,873.000000,4.668400e+04,0.587000,-13.400000,-21.000000,0.000000,NaN,NaN
25%,13.250000,3.189780e+05,23992.500000,2.739074e+07,959.500000,1.612870e+05,0.684500,-9.400000,416.375000,6.000000,NaN,NaN
50%,26.500000,8.172720e+05,66843.000000,7.207220e+07,1015.000000,3.706480e+05,0.724000,-7.100000,1372.744000,10.000000,NaN,NaN
75%,39.750000,1.259598e+06,114565.500000,1.127716e+08,1074.000000,6.813695e+05,0.747500,-5.800000,2418.271000,19.500000,NaN,NaN
max,53.000000,5.829777e+06,419078.000000,4.376307e+08,1264.000000,2.202117e+06,0.808000,0.700000,8407.361000,49.000000,NaN,NaN

In [517]:
df.head()
column_list = list(df.columns)
column_list

['index',
 'State',
 'Medicare Enrollment (Sept. 2016)',
 'Medicare Beneficiaries benefitting from donut hole savings (2015)',
 'Total Medicare beneficiary savings from donut hole (2015)',
 'Average per Medicare Beneficiary Donut Hole Savings (2015)',
 'Part B Beneficiaries Using Free Preventive Services (2015)',
 'Share of Part B Beneficiaries Using Free Preventive Services (2015)',
 '% Change in Hospital Readmission Rates Among Medicare Beneficiaries (2010-2015)',
 'Avoided Readmissions (2015)',
 'Number of Accountable Care Organizations (2016)',
 'Unnamed: 10',
 'Unnamed: 11']

In [519]:
df = df.drop(['Unnamed: 10', 'Unnamed: 11'], axis=1)
print(df)

    index                 State  Medicare Enrollment (Sept. 2016)  \
0       0              Alabama                           989855.0
1       1               Alaska                            88966.0
2       2              Arizona                          1175624.0
3       3             Arkansas                           606146.0
4       4            California                         5829777.0
5       5              Colorado                          820234.0
6       6           Connecticut                          644136.0
7       7             Delaware                           186835.0
8       8  District of Columbia                           90492.0
9       9              Florida                          4149593.0
10     10              Georgia                          1574058.0
11     11                Hawaii                          252514.0
12     12                 Idaho                          294284.0
13     13             Illinois                          2118300.0
14     14              Indiana                          1181014.0
15     15                 Iowa                           587780.0
16     16               Kansas                           499753.0
17     17              Kentucky                          881938.0
18     18            Louisiana                           817272.0
19     19                Maine                           315160.0
20     20              Maryland                          960848.0
21     21         Massachusetts                         1252277.0
22     22             Michigan                          1947787.0
23     23             Minnesota                          944222.0
24     24          Mississippi                           571699.0
25     25             Missouri                          1163543.0
26     26              Montana                           209389.0
27     27             Nebraska                           322796.0
28     28                Nevada                          471747.0
29     29        New Hampshire                           275803.0
30     30           New Jersey                          1528961.0
31     31            New Mexico                          385918.0
32     32              New York                         3424666.0
33     33       North Carolina                          1823454.0
34     34         North Dakota                           122294.0
35     35                 Ohio                          2208504.0
36     36             Oklahoma                           693677.0
37     37                Oregon                          784032.0
38     38         Pennsylvania                          2588577.0
39     39          Rhode Island                          208324.0
40     40       South Carolina                           974114.0
41     41         South Dakota                           161464.0
42     42            Tennessee                          1266920.0
43     43                Texas                          3765946.0
44     44                 Utah                           358887.0
45     45               Vermont                          136021.0
46     46             Virginia                          1392261.0
47     47            Washington                         1238649.0
48     48        West Virginia                           423500.0
49     49            Wisconsin                          1084854.0
50     50               Wyoming                           99128.0
51     51                   NaN                               NaN
52     52                   NaN                               NaN
53     53                   NaN                               NaN

    Medicare Beneficiaries benefitting from donut hole savings (2015)  \
0                                             90556.0
1                                              3094.0
2                                             96954.0
3                                             40658.0
4                                            419078.0
5                                             59459.0
6                                             66843.0
7                                             24223.0
8                                              3258.0
9                                            355360.0
10                                           141609.0
11                                            23762.0
12                                            19821.0
13                                           196727.0
14                                           123302.0
15                                            55670.0
16                                            46642.0
17                                            89343.0
18                                            73530.0
19                                            18970.0
20                                            86073.0
21                                            83303.0
22                                           212075.0
23                                            73484.0
24                                            41041.0
25                                           107008.0
26                                            13384.0
27                                            30366.0
28                                            34285.0
29                                            21026.0
30                                           211881.0
31                                            23642.0
32                                           359127.0
33                                           173412.0
34                                            11866.0
35                                           237303.0
36                                            65788.0
37                                            54007.0
38                                           297606.0
39                                            15785.0
40                                            98589.0
41                                            13616.0
42                                           114993.0
43                                           346750.0
44                                            28336.0
45                                            10955.0
46                                           114138.0
47                                            74902.0
48                                            45280.0
49                                            90303.0
50                                             8008.0
51                                                NaN
52                                                NaN
53                                                NaN

    Total Medicare beneficiary savings from donut hole (2015)  \
0                                          97330073.0
1                                           3184420.0
2                                          93694466.0
3                                          36436080.0
4                                         437630655.0
5                                          58449048.0
6                                          78487237.0
7                                          28586178.0
8                                           3496014.0
9                                         350888326.0
10                                        148784101.0
11                                         30027279.0
12                                         17584133.0
13                                        204732932.0
14                                        127674560.0
15                                         53282941.0
16                                         43407473.0
17                                         99034242.0
18                                         72702732.0
19                                         18712752.0
20                                         99702303.0
21                                         86517318.0
22                                        249358887.0
23                                         72072204.0
24                                         35832183.0
25                                        102895608.0
26                                         12097212.0
27                                         27674906.0
28                                         33160363.0
29                                         22023187.0
30                                        262865304.0
31                                         23792440.0
32                                        429276680.0
33                                        175662465.0
34                                         11470436.0
35                                        258550550.0
36                                         67925763.0
37                                         50494389.0
38                                        313453847.0
39                                         14392653.0
40                                        107311751.0
41                                         12395059.0
42                                        109733424.0
43                                        366381273.0
44                                         27106568.0
45                                         12077364.0
46                                        115809752.0
47                                         73272041.0
48                                         54194138.0
49                                         93517959.0
50                                          7634708.0
51                                                NaN
52                                                NaN
53                                                NaN

    Average per Medicare Beneficiary Donut Hole Savings (2015)  \
0                                              1075.0
1                                              1029.0
2                                               966.0
3                                               896.0
4                                              1044.0
5                                               983.0
6                                              1174.0
7                                              1180.0
8                                              1073.0
9                                               987.0
10                                             1051.0
11                                             1264.0
12                                              887.0
13                                             1041.0
14                                             1035.0
15                                              957.0
16                                              931.0
17                                             1108.0
18                                              989.0
19                                              986.0
20                                             1158.0
21                                             1039.0
22                                             1176.0
23                                              981.0
24                                              873.0
25                                              962.0
26                                              904.0
27                                              911.0
28                                              967.0
29                                             1047.0
30                                             1241.0
31                                             1006.0
32                                             1195.0
33                                             1013.0
34                                              967.0
35                                             1090.0
36                                             1032.0
37                                              935.0
38                                             1053.0
39                                              912.0
40                                             1088.0
41                                              910.0
42                                              954.0
43                                             1057.0
44                                              957.0
45                                             1102.0
46                                             1015.0
47                                              978.0
48                                             1197.0
49                                             1036.0
50                                              953.0
51                                                NaN
52                                                NaN
53                                                NaN

    Part B Beneficiaries Using Free Preventive Services (2015)  \
0                                            531567.0
1                                             46876.0
2                                            481230.0
3                                            337214.0
4                                           2202117.0
5                                            323128.0
6                                            344091.0
7                                            133283.0
8                                             46684.0
9                                           1826053.0
10                                           751478.0
11                                            79163.0
12                                           121236.0
13                                          1185594.0
14                                           637488.0
15                                           370648.0
16                                           299776.0
17                                           461771.0
18                                           387587.0
19                                           165892.0
20                                           604509.0
21                                           725251.0
22                                           949718.0
23                                           271698.0
24                                           345847.0
25                                           580049.0
26                                           106395.0
27                                           193448.0
28                                           187012.0
29                                           176282.0
30                                           940537.0
31                                           156682.0
32                                          1486645.0
33                                           950381.0
34                                            71547.0
35                                           885625.0
36                                           388681.0
37                                           269101.0
38                                          1081445.0
39                                            92065.0
40                                           549051.0
41                                            87816.0
42                                           600644.0
43                                          1746043.0
44                                           146179.0
45                                            87184.0
46                                           813642.0
47                                           543203.0
48                                           213916.0
49                                           481012.0
50                                            56898.0
51                                                NaN
52                                                NaN
53                                                NaN

    Share of Part B Beneficiaries Using Free Preventive Services (2015)  \
0                                               0.742
1                                               0.587
2                                               0.703
3                                               0.712
4                                               0.685
5                                               0.676
6                                               0.773
7                                               0.808
8                                               0.675
9                                               0.752
10                                              0.728
11                                              0.672
12                                              0.646
13                                              0.744
14                                              0.733
15                                              0.767
16                                              0.724
17                                              0.731
18                                              0.713
19                                              0.714
20                                              0.758
21                                              0.789
22                                              0.741
23                                              0.684
24                                              0.716
25                                              0.728
26                                              0.653
27                                              0.718
28                                              0.649
29                                              0.744
30                                              0.772
31                                              0.634
32                                              0.744
33                                              0.765
34                                              0.729
35                                              0.716
36                                              0.706
37                                              0.664
38                                              0.747
39                                              0.764
40                                              0.756
41                                              0.699
42                                              0.748
43                                              0.717
44                                              0.679
45                                              0.728
46                                              0.762
47                                              0.681
48                                              0.707
49                                              0.751
50                                              0.621
51                                                NaN
52                                                NaN
53                                                NaN

    % Change in Hospital Readmission Rates Among Medicare Beneficiaries (2010-2015)  \
0                                                -5.8
1                                                -5.5
2                                               -10.8
3                                                -6.2
4                                                -5.7
5                                                -9.2
6                                                -7.7
7                                               -10.3
8                                                -7.5
9                                                -2.7
10                                               -7.4
11                                              -13.4
12                                               -2.4
13                                              -12.1
14                                               -7.5
15                                               -6.5
16                                               -9.8
17                                               -9.1
18                                               -9.6
19                                               -3.7
20                                              -10.4
21                                               -5.8
22                                               -3.2
23                                               -7.0

In [520]:
print(df.isna().sum())

index                                                                              0
State                                                                              3
Medicare Enrollment (Sept. 2016)                                                   3
Medicare Beneficiaries benefitting from donut hole savings (2015)                  3
Total Medicare beneficiary savings from donut hole (2015)                          3
Average per Medicare Beneficiary Donut Hole Savings (2015)                         3
Part B Beneficiaries Using Free Preventive Services (2015)                         3
Share of Part B Beneficiaries Using Free Preventive Services (2015)                3
% Change in Hospital Readmission Rates Among Medicare Beneficiaries (2010-2015)    3
Avoided Readmissions (2015)                                                        3
Number of Accountable Care Organizations (2016)                                    3
dtype: int64

In [522]:
df = df.dropna()

In [523]:
df

,index,State,Medicare Enrollment (Sept. 2016),Medicare Beneficiaries benefitting from donut hole savings (2015),Total Medicare beneficiary savings from donut hole (2015),Average per Medicare Beneficiary Donut Hole Savings (2015),Part B Beneficiaries Using Free Preventive Services (2015),Share of Part B Beneficiaries Using Free Preventive Services (2015),% Change in Hospital Readmission Rates Among Medicare Beneficiaries (2010-2015),Avoided Readmissions (2015),Number of Accountable Care Organizations (2016)
0,0,Alabama,989855.0,90556.0,97330073.0,1075.0,531567.0,0.742,-5.8,1503.120,9.0
1,1,Alaska,88966.0,3094.0,3184420.0,1029.0,46876.0,0.587,-5.5,78.330,1.0
2,2,Arizona,1175624.0,96954.0,93694466.0,966.0,481230.0,0.703,-10.8,2270.126,10.0
3,3,Arkansas,606146.0,40658.0,36436080.0,896.0,337214.0,0.712,-6.2,993.474,11.0
4,4,California,5829777.0,419078.0,437630655.0,1044.0,2202117.0,0.685,-5.7,5580.208,29.0
5,5,Colorado,820234.0,59459.0,58449048.0,983.0,323128.0,0.676,-9.2,1098.724,7.0
6,6,Connecticut,644136.0,66843.0,78487237.0,1174.0,344091.0,0.773,-7.7,1306.052,12.0
7,7,Delaware,186835.0,24223.0,28586178.0,1180.0,133283.0,0.808,-10.3,574.718,7.0
8,8,District of Columbia,90492.0,3258.0,3496014.0,1073.0,46684.0,0.675,-7.5,345.800,8.0
9,9,Florida,4149593.0,355360.0,350888326.0,987.0,1826053.0,0.752,-2.7,3161.034,49.0
10,10,Georgia,1574058.0,141609.0,148784101.0,1051.0,751478.0,0.728,-7.4,2452.875,19.0
11,11,Hawaii,252514.0,23762.0,30027279.0,1264.0,79163.0,0.672,-13.4,315.051,0.0
12,12,Idaho,294284.0,19821.0,17584133.0,887.0,121236.0,0.646,-2.4,78.375,5.0
13,13,Illinois,2118300.0,196727.0,204732932.0,1041.0,1185594.0,0.744,-12.1,8107.780,29.0
14,14,Indiana,1181014.0,123302.0,127674560.0,1035.0,637488.0,0.733,-7.5,2473.934,24.0
15,15,Iowa,587780.0,55670.0,53282941.0,957.0,370648.0,0.767,-6.5,909.680,9.0
16,16,Kansas,499753.0,46642.0,43407473.0,931.0,299776.0,0.724,-9.8,1360.512,9.0
17,17,Kentucky,881938.0,89343.0,99034242.0,1108.0,461771.0,0.731,-9.1,2383.667,22.0
18,18,Louisiana,817272.0,73530.0,72702732.0,989.0,387587.0,0.713,-9.6,2013.336,10.0
19,19,Maine,315160.0,18970.0,18712752.0,986.0,165892.0,0.714,-3.7,231.931,6.0
20,20,Maryland,960848.0,86073.0,99702303.0,1158.0,604509.0,0.758,-10.4,3788.610,26.0
21,21,Massachusetts,1252277.0,83303.0,86517318.0,1039.0,725251.0,0.789,-5.8,2213.310,14.0
22,22,Michigan,1947787.0,212075.0,249358887.0,1176.0,949718.0,0.741,-3.2,1767.272,25.0
23,23,Minnesota,944222.0,73484.0,72072204.0,981.0,271698.0,0.684,-7.0,1434.825,8.0
24,24,Mississippi,571699.0,41041.0,35832183.0,873.0,345847.0,0.716,-7.9,1469.132,11.0
25,25,Missouri,1163543.0,107008.0,102895608.0,962.0,580049.0,0.728,-7.1,2311.214,13.0
26,26,Montana,209389.0,13384.0,12097212.0,904.0,106395.0,0.653,-5.8,231.002,4.0
27,27,Nebraska,322796.0,30366.0,27674906.0,911.0,193448.0,0.718,-8.3,735.187,7.0
28,28,Nevada,471747.0,34285.0,33160363.0,967.0,187012.0,0.649,-5.6,529.440,7.0
29,29,New Hampshire,275803.0,21026.0,22023187.0,1047.0,176282.0,0.744,-2.5,151.747,8.0
30,30,New Jersey,1528961.0,211881.0,262865304.0,1241.0,940537.0,0.772,-13.3,6773.572,29.0
31,31,New Mexico,385918.0,23642.0,23792440.0,1006.0,156682.0,0.634,-2.6,118.432,3.0
32,32,New York,3424666.0,359127.0,429276680.0,1195.0,1486645.0,0.744,-10.6,8407.361,38.0
33,33,North Carolina,1823454.0,173412.0,175662465.0,1013.0,950381.0,0.765,-6.5,2472.110,20.0
34,34,North Dakota,122294.0,11866.0,11470436.0,967.0,71547.0,0.729,-6.5,267.100,3.0
35,35,Ohio,2208504.0,237303.0,258550550.0,1090.0,885625.0,0.716,-10.6,5404.684,19.0
36,36,Oklahoma,693677.0,65788.0,67925763.0,1032.0,388681.0,0.706,-10.3,1877.702,7.0
37,37,Oregon,784032.0,54007.0,50494389.0,935.0,269101.0,0.664,-0.7,75.199,4.0
38,38,Pennsylvania,2588577.0,297606.0,313453847.0,1053.0,1081445.0,0.747,-8.3,4995.046,27.0
39,39,Rhode Island,208324.0,15785.0,14392653.0,912.0,92065.0,0.764,-10.5,486.950,5.0
40,40,South Carolina,974114.0,98589.0,107311751.0,1088.0,549051.0,0.756,-6.1,1236.845,12.0
41,41,South Dakota,161464.0,13616.0,12395059.0,910.0,87816.0,0.699,-11.4,515.094,3.0
42,42,Tennessee,1266920.0,114993.0,109733424.0,954.0,600644.0,0.748,-8.7,2904.544,15.0
43,43,Texas,3765946.0,346750.0,366381273.0,1057.0,1746043.0,0.717,-5.8,4960.198,37.0
44,44,Utah,358887.0,28336.0,27106568.0,957.0,146179.0,0.679,-5.7,261.324,3.0
45,45,Vermont,136021.0,10955.0,12077364.0,1102.0,87184.0,0.728,0.7,-21.000,3.0
46,46,Virginia,1392261.0,114138.0,115809752.0,1015.0,813642.0,0.762,-6.3,2301.950,25.0
47,47,Washington,1238649.0,74902.0,73272041.0,978.0,543203.0,0.681,-7.2,1388.001,6.0
48,48,West Virginia,423500.0,45280.0,54194138.0,1197.0,213916.0,0.707,-6.5,777.370,11.0
49,49,Wisconsin,1084854.0,90303.0,93517959.0,1036.0,481012.0,0.751,-7.1,1372.744,13.0
50,50,Wyoming,99128.0,8008.0,7634708.0,953.0,56898.0,0.621,-6.0,109.538,3.0

DATASET #2

In [437]:
import pandas as pd

df = pd.read_csv('the-number-of-estimated-eligible-uninsured-people-for-outreach-targeting.csv')
df.head()
print(df)

      StateName  StateFIPS  PumaState  PUMA  \
0       Alabama          1     100100   100
1       Alabama          1     100200   200
2       Alabama          1     100300   300
3       Alabama          1     100400   400
4       Alabama          1     100500   500
...         ...        ...        ...   ...
2064  Wisconsin         55    5502500  2500
2065    Wyoming         56    5600100   100
2066    Wyoming         56    5600200   200
2067    Wyoming         56    5600300   300
2068    Wyoming         56    5600400   400

                                   Counties Within PUMA  uninsured_total  \
0                     Lauderdale County, Colbert County            18517
1                                 Madison County (part)            28109
2                                 Madison County (part)            26568
3                         DeKalb County, Jackson County            21245
4       Marshall County, Cullman County, Winston County            25654
...                                                 ...              ...
2064                                   Sheboygan County            10295
2065  Sweetwater County, Park County, Uinta County, ...            22304
2066      Natrona County, Fremont County, Carbon County            21554
2067  Campbell County, Sheridan County, Goshen Count...            23115
2068                      Laramie County, Albany County            15521

      uninsured_percent  Foodstamp  Age0_18  Age19_25  ...  EnglishSpeaking  \
0                  15.3     7754.0    445.0      4358  ...            17665
1                  19.0     8364.0   1506.0      4865  ...            27579
2                  12.1     6620.0   1147.0      4786  ...            25729
3                  20.4     6330.0   6713.0      2582  ...            20800
4                  16.0     8155.0   3627.0      5429  ...            24218
...                 ...        ...      ...       ...  ...              ...
2064               10.7     3780.0    583.0      2172  ...             9372
2065               18.2     2569.0   3311.0      2179  ...            21822
2066               18.6     5207.0   3298.0      3254  ...            21398
2067               16.7     3057.0   3272.0      3710  ...            22658
2068               13.6     1147.0   1939.0      3833  ...            15462

     Spanish Chinese Korean Vietnamese Tagalog Russian OtherLang  \
0      852.0    -       NaN        NaN     NaN     NaN       NaN
1      491.0    -       NaN       38.0     NaN     NaN       NaN
2      839.0    -       NaN        NaN     NaN     NaN       NaN
3      446.0    -       NaN        NaN     NaN     NaN       NaN
4     1313.0       7    NaN        NaN    24.0     NaN      92.0
...      ...     ...    ...        ...     ...     ...       ...
2064   220.0    -       NaN        NaN     NaN     NaN     703.0
2065   482.0    -       NaN        NaN     NaN     NaN       NaN
2066   157.0    -       NaN        NaN     NaN     NaN       NaN
2067   302.0     155    NaN        NaN     NaN     NaN       NaN
2068    58.0    -       NaN        NaN     NaN     NaN       NaN

     SpeaksMostCommonOthLang OtherLanguage
0                        NaN            **
1                        NaN            **
2                        NaN            **
3                        NaN            **
4                        NaN            **
...                      ...           ...
2064                   416.0      Albanian
2065                     NaN            **
2066                     NaN            **
2067                     NaN            **
2068                     NaN            **

[2069 rows x 52 columns]

In [438]:
import pandas as pd

df = pd.read_csv('the-number-of-estimated-eligible-uninsured-people-for-outreach-targeting.csv')
df.describe()
print(df)

      StateName  StateFIPS  PumaState  PUMA  \
0       Alabama          1     100100   100
1       Alabama          1     100200   200
2       Alabama          1     100300   300
3       Alabama          1     100400   400
4       Alabama          1     100500   500
...         ...        ...        ...   ...
2064  Wisconsin         55    5502500  2500
2065    Wyoming         56    5600100   100
2066    Wyoming         56    5600200   200
2067    Wyoming         56    5600300   300
2068    Wyoming         56    5600400   400

                                   Counties Within PUMA  uninsured_total  \
0                     Lauderdale County, Colbert County            18517
1                                 Madison County (part)            28109
2                                 Madison County (part)            26568
3                         DeKalb County, Jackson County            21245
4       Marshall County, Cullman County, Winston County            25654
...                                                 ...              ...
2064                                   Sheboygan County            10295
2065  Sweetwater County, Park County, Uinta County, ...            22304
2066      Natrona County, Fremont County, Carbon County            21554
2067  Campbell County, Sheridan County, Goshen Count...            23115
2068                      Laramie County, Albany County            15521

      uninsured_percent  Foodstamp  Age0_18  Age19_25  ...  EnglishSpeaking  \
0                  15.3     7754.0    445.0      4358  ...            17665
1                  19.0     8364.0   1506.0      4865  ...            27579
2                  12.1     6620.0   1147.0      4786  ...            25729
3                  20.4     6330.0   6713.0      2582  ...            20800
4                  16.0     8155.0   3627.0      5429  ...            24218
...                 ...        ...      ...       ...  ...              ...
2064               10.7     3780.0    583.0      2172  ...             9372
2065               18.2     2569.0   3311.0      2179  ...            21822
2066               18.6     5207.0   3298.0      3254  ...            21398
2067               16.7     3057.0   3272.0      3710  ...            22658
2068               13.6     1147.0   1939.0      3833  ...            15462

     Spanish Chinese Korean Vietnamese Tagalog Russian OtherLang  \
0      852.0    -       NaN        NaN     NaN     NaN       NaN
1      491.0    -       NaN       38.0     NaN     NaN       NaN
2      839.0    -       NaN        NaN     NaN     NaN       NaN
3      446.0    -       NaN        NaN     NaN     NaN       NaN
4     1313.0       7    NaN        NaN    24.0     NaN      92.0
...      ...     ...    ...        ...     ...     ...       ...
2064   220.0    -       NaN        NaN     NaN     NaN     703.0
2065   482.0    -       NaN        NaN     NaN     NaN       NaN
2066   157.0    -       NaN        NaN     NaN     NaN       NaN
2067   302.0     155    NaN        NaN     NaN     NaN       NaN
2068    58.0    -       NaN        NaN     NaN     NaN       NaN

     SpeaksMostCommonOthLang OtherLanguage
0                        NaN            **
1                        NaN            **
2                        NaN            **
3                        NaN            **
4                        NaN            **
...                      ...           ...
2064                   416.0      Albanian
2065                     NaN            **
2066                     NaN            **
2067                     NaN            **
2068                     NaN            **

[2069 rows x 52 columns]

In [457]:
import pandas as pd
df = pd.read_csv('the-number-of-estimated-eligible-uninsured-people-for-outreach-targeting.csv')
df.info()
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2069 entries, 0 to 2068
Data columns (total 52 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   StateName                      2069 non-null   object
 1   StateFIPS                      2069 non-null   int64
 2   PumaState                      2069 non-null   int64
 3   PUMA                           2069 non-null   int64
 4   Counties Within PUMA           2069 non-null   object
 5   uninsured_total                2069 non-null   int64
 6   uninsured_percent              2069 non-null   float64
 7   Foodstamp                      2058 non-null   float64
 8   Age0_18                        2061 non-null   float64
 9   Age19_25                       2069 non-null   int64
 10  Age26_34                       2068 non-null   float64
 11  Age35_54                       2069 non-null   object
 12  Age55_64                       2069 non-null   object
 13  138PctFPL_or_Less              2069 non-null   object
 14  139to400PctFPL                 2069 non-null   object
 15  Above400PctFPL                 2069 non-null   object
 16  Male                           2069 non-null   object
 17  Female                         2069 non-null   object
 18  Married                        2069 non-null   object
 19  ChildinFamily                  2069 non-null   object
 20  Latino                         2069 non-null   object
 21  WhiteNonLatino                 2069 non-null   object
 22  BlackNonLatino                 2069 non-null   object
 23  AsianNonLatino                 2069 non-null   object
 24  HawaiiPacIslander              2069 non-null   object
 25  AmericanIndian_AlaskaNative    2069 non-null   object
 26  Multiracial_or_Other           2069 non-null   object
 27  Disabled                       2069 non-null   object
 28  FullTime_Worker_in_Family      2069 non-null   object
 29  Job_Agriculture                2069 non-null   object
 30  Job_Mining                     2069 non-null   object
 31  Job_ManufacturingConstruction  2069 non-null   object
 32  Job_Trade                      2069 non-null   object
 33  Job_InfoFinance                2069 non-null   object
 34  Job_EducHealth                 2069 non-null   object
 35  Job_Entertainment              2069 non-null   object
 36  Job_Service                    2069 non-null   object
 37  Job_MilitaryPublic             2069 non-null   object
 38  LessThanHS                     2069 non-null   object
 39  HSDiploma                      2069 non-null   object
 40  CollegeGrad                    2069 non-null   object
 41  NoEnglishAdults_in_House       1984 non-null   float64
 42  EnglishSpeaking                2069 non-null   int64
 43  Spanish                        1878 non-null   float64
 44  Chinese                        2069 non-null   object
 45  Korean                         418 non-null    float64
 46  Vietnamese                     479 non-null    float64
 47  Tagalog                        318 non-null    float64
 48  Russian                        264 non-null    float64
 49  OtherLang                      1622 non-null   float64
 50  SpeaksMostCommonOthLang        1211 non-null   float64
 51  OtherLanguage                  2069 non-null   object
dtypes: float64(12), int64(6), object(34)
memory usage: 840.7+ KB
      StateName  StateFIPS  PumaState  PUMA  \
0       Alabama          1     100100   100
1       Alabama          1     100200   200
2       Alabama          1     100300   300
3       Alabama          1     100400   400
4       Alabama          1     100500   500
...         ...        ...        ...   ...
2064  Wisconsin         55    5502500  2500
2065    Wyoming         56    5600100   100
2066    Wyoming         56    5600200   200
2067    Wyoming         56    5600300   300
2068    Wyoming         56    5600400   400

                                   Counties Within PUMA  uninsured_total  \
0                     Lauderdale County, Colbert County            18517
1                                 Madison County (part)            28109
2                                 Madison County (part)            26568
3                         DeKalb County, Jackson County            21245
4       Marshall County, Cullman County, Winston County            25654
...                                                 ...              ...
2064                                   Sheboygan County            10295
2065  Sweetwater County, Park County, Uinta County, ...            22304
2066      Natrona County, Fremont County, Carbon County            21554
2067  Campbell County, Sheridan County, Goshen Count...            23115
2068                      Laramie County, Albany County            15521

      uninsured_percent  Foodstamp  Age0_18  Age19_25  ...  EnglishSpeaking  \
0                  15.3     7754.0    445.0      4358  ...            17665
1                  19.0     8364.0   1506.0      4865  ...            27579
2                  12.1     6620.0   1147.0      4786  ...            25729
3                  20.4     6330.0   6713.0      2582  ...            20800
4                  16.0     8155.0   3627.0      5429  ...            24218
...                 ...        ...      ...       ...  ...              ...
2064               10.7     3780.0    583.0      2172  ...             9372
2065               18.2     2569.0   3311.0      2179  ...            21822
2066               18.6     5207.0   3298.0      3254  ...            21398
2067               16.7     3057.0   3272.0      3710  ...            22658
2068               13.6     1147.0   1939.0      3833  ...            15462

     Spanish Chinese Korean Vietnamese Tagalog Russian OtherLang  \
0      852.0    -       NaN        NaN     NaN     NaN       NaN
1      491.0    -       NaN       38.0     NaN     NaN       NaN
2      839.0    -       NaN        NaN     NaN     NaN       NaN
3      446.0    -       NaN        NaN     NaN     NaN       NaN
4     1313.0       7    NaN        NaN    24.0     NaN      92.0
...      ...     ...    ...        ...     ...     ...       ...
2064   220.0    -       NaN        NaN     NaN     NaN     703.0
2065   482.0    -       NaN        NaN     NaN     NaN       NaN
2066   157.0    -       NaN        NaN     NaN     NaN       NaN
2067   302.0     155    NaN        NaN     NaN     NaN       NaN
2068    58.0    -       NaN        NaN     NaN     NaN       NaN

     SpeaksMostCommonOthLang OtherLanguage
0                        NaN            **
1                        NaN            **
2                        NaN            **
3                        NaN            **
4                        NaN            **
...                      ...           ...
2064                   416.0      Albanian
2065                     NaN            **
2066                     NaN            **
2067                     NaN            **
2068                     NaN            **

[2069 rows x 52 columns]

In [458]:
df.head()
column_list = list(df.columns)
column_list

['StateName',
 'StateFIPS',
 'PumaState',
 'PUMA',
 'Counties Within PUMA',
 'uninsured_total',
 'uninsured_percent',
 'Foodstamp',
 'Age0_18',
 'Age19_25',
 'Age26_34',
 'Age35_54',
 'Age55_64',
 '138PctFPL_or_Less',
 '139to400PctFPL',
 'Above400PctFPL',
 'Male',
 'Female',
 'Married',
 'ChildinFamily',
 'Latino',
 'WhiteNonLatino',
 'BlackNonLatino',
 'AsianNonLatino',
 'HawaiiPacIslander',
 'AmericanIndian_AlaskaNative',
 'Multiracial_or_Other',
 'Disabled',
 'FullTime_Worker_in_Family',
 'Job_Agriculture',
 'Job_Mining',
 'Job_ManufacturingConstruction',
 'Job_Trade',
 'Job_InfoFinance',
 'Job_EducHealth',
 'Job_Entertainment',
 'Job_Service',
 'Job_MilitaryPublic',
 'LessThanHS',
 'HSDiploma',
 'CollegeGrad',
 'NoEnglishAdults_in_House',
 'EnglishSpeaking',
 'Spanish',
 'Chinese',
 'Korean',
 'Vietnamese',
 'Tagalog',
 'Russian',
 'OtherLang',
 'SpeaksMostCommonOthLang',
 'OtherLanguage']

In [459]:
print(df.shape)

(2069, 52)

In [460]:
print(df.columns)

Index(['StateName', 'StateFIPS', 'PumaState', 'PUMA', 'Counties Within PUMA',
       'uninsured_total', 'uninsured_percent', 'Foodstamp', 'Age0_18',
       'Age19_25', 'Age26_34', 'Age35_54', 'Age55_64', '138PctFPL_or_Less',
       '139to400PctFPL', 'Above400PctFPL', 'Male', 'Female', 'Married',
       'ChildinFamily', 'Latino', 'WhiteNonLatino', 'BlackNonLatino',
       'AsianNonLatino', 'HawaiiPacIslander', 'AmericanIndian_AlaskaNative',
       'Multiracial_or_Other', 'Disabled', 'FullTime_Worker_in_Family',
       'Job_Agriculture', 'Job_Mining', 'Job_ManufacturingConstruction',
       'Job_Trade', 'Job_InfoFinance', 'Job_EducHealth', 'Job_Entertainment',
       'Job_Service', 'Job_MilitaryPublic', 'LessThanHS', 'HSDiploma',
       'CollegeGrad', 'NoEnglishAdults_in_House', 'EnglishSpeaking', 'Spanish',
       'Chinese', 'Korean', 'Vietnamese', 'Tagalog', 'Russian', 'OtherLang',
       'SpeaksMostCommonOthLang', 'OtherLanguage'],
      dtype='object')

In [462]:
df = df.drop(['138PctFPL_or_Less', '139to400PctFPL', 'Above400PctFPL', 'HawaiiPacIslander', 'AmericanIndian_AlaskaNative',
       'Job_Agriculture', 'Job_Mining', 'Job_ManufacturingConstruction', 'Job_Trade', 'Job_InfoFinance', 'Job_EducHealth', 'Job_Entertainment', 'Job_Service', 'Job_MilitaryPublic',
       'Chinese', 'Korean', 'Vietnamese', 'Tagalog', 'Russian', 'OtherLang', 'SpeaksMostCommonOthLang','OtherLanguage'], axis=1)
print(df)

      StateName  StateFIPS  PumaState  PUMA  \
0       Alabama          1     100100   100
1       Alabama          1     100200   200
2       Alabama          1     100300   300
3       Alabama          1     100400   400
4       Alabama          1     100500   500
...         ...        ...        ...   ...
2064  Wisconsin         55    5502500  2500
2065    Wyoming         56    5600100   100
2066    Wyoming         56    5600200   200
2067    Wyoming         56    5600300   300
2068    Wyoming         56    5600400   400

                                   Counties Within PUMA  uninsured_total  \
0                     Lauderdale County, Colbert County            18517
1                                 Madison County (part)            28109
2                                 Madison County (part)            26568
3                         DeKalb County, Jackson County            21245
4       Marshall County, Cullman County, Winston County            25654
...                                                 ...              ...
2064                                   Sheboygan County            10295
2065  Sweetwater County, Park County, Uinta County, ...            22304
2066      Natrona County, Fremont County, Carbon County            21554
2067  Campbell County, Sheridan County, Goshen Count...            23115
2068                      Laramie County, Albany County            15521

      uninsured_percent  Foodstamp  Age0_18  Age19_25  ...  AsianNonLatino  \
0                  15.3     7754.0    445.0      4358  ...              9
1                  19.0     8364.0   1506.0      4865  ...            570
2                  12.1     6620.0   1147.0      4786  ...            120
3                  20.4     6330.0   6713.0      2582  ...            -
4                  16.0     8155.0   3627.0      5429  ...            332
...                 ...        ...      ...       ...  ...             ...
2064               10.7     3780.0    583.0      2172  ...            541
2065               18.2     2569.0   3311.0      2179  ...            -
2066               18.6     5207.0   3298.0      3254  ...            -
2067               16.7     3057.0   3272.0      3710  ...            155
2068               13.6     1147.0   1939.0      3833  ...            -

     Multiracial_or_Other Disabled FullTime_Worker_in_Family LessThanHS  \
0                    -      3,484                    13,213      3,557
1                    323    3,822                    19,728      5,363
2                    518    2,889                    17,397      5,703
3                    403    2,428                    15,651      7,939
4                    287    3,694                    19,066      7,870
...                   ...      ...                       ...        ...
2064                 140      670                     6,844      1,754
2065                 429    1,393                    20,453      1,830
2066               1,439    2,039                    18,831      3,979
2067                 238    2,572                    19,224      3,259
2068                  89    1,173                    12,975      1,659

     HSDiploma CollegeGrad NoEnglishAdults_in_House EnglishSpeaking Spanish
0      13,685       1,275                     783.0           17665   852.0
1      19,910       2,835                     360.0           27579   491.0
2      18,290       2,574                     672.0           25729   839.0
3      13,059         247                     135.0           20800   446.0
4      17,006         778                    1236.0           24218  1313.0
...        ...         ...                      ...             ...     ...
2064    7,539       1,003                     596.0            9372   220.0
2065   18,816       1,658                     502.0           21822   482.0
2066   15,762       1,813                     202.0           21398   157.0
2067   18,551       1,305                     493.0           22658   302.0
2068   11,555       2,306                     127.0           15462    58.0

[2069 rows x 30 columns]

In [461]:
print(df.isna().sum())

StateName                           0
StateFIPS                           0
PumaState                           0
PUMA                                0
Counties Within PUMA                0
uninsured_total                     0
uninsured_percent                   0
Foodstamp                          11
Age0_18                             8
Age19_25                            0
Age26_34                            1
Age35_54                            0
Age55_64                            0
138PctFPL_or_Less                   0
139to400PctFPL                      0
Above400PctFPL                      0
Male                                0
Female                              0
Married                             0
ChildinFamily                       0
Latino                              0
WhiteNonLatino                      0
BlackNonLatino                      0
AsianNonLatino                      0
HawaiiPacIslander                   0
AmericanIndian_AlaskaNative         0
Multiracial_or_Other                0
Disabled                            0
FullTime_Worker_in_Family           0
Job_Agriculture                     0
Job_Mining                          0
Job_ManufacturingConstruction       0
Job_Trade                           0
Job_InfoFinance                     0
Job_EducHealth                      0
Job_Entertainment                   0
Job_Service                         0
Job_MilitaryPublic                  0
LessThanHS                          0
HSDiploma                           0
CollegeGrad                         0
NoEnglishAdults_in_House           85
EnglishSpeaking                     0
Spanish                           191
Chinese                             0
Korean                           1651
Vietnamese                       1590
Tagalog                          1751
Russian                          1805
OtherLang                         447
SpeaksMostCommonOthLang           858
OtherLanguage                       0
dtype: int64

In [463]:
df = df.dropna(subset = ["Foodstamp", "Age0_18", "Age26_34", "Spanish", "NoEnglishAdults_in_House"])

In [464]:
df.isna().sum()

StateName                    0
StateFIPS                    0
PumaState                    0
PUMA                         0
Counties Within PUMA         0
uninsured_total              0
uninsured_percent            0
Foodstamp                    0
Age0_18                      0
Age19_25                     0
Age26_34                     0
Age35_54                     0
Age55_64                     0
Male                         0
Female                       0
Married                      0
ChildinFamily                0
Latino                       0
WhiteNonLatino               0
BlackNonLatino               0
AsianNonLatino               0
Multiracial_or_Other         0
Disabled                     0
FullTime_Worker_in_Family    0
LessThanHS                   0
HSDiploma                    0
CollegeGrad                  0
NoEnglishAdults_in_House     0
EnglishSpeaking              0
Spanish                      0
dtype: int64

In [465]:
df.duplicated().sum()

np.int64(0)

In [466]:
df = df.drop_duplicates()
print(df)

      StateName  StateFIPS  PumaState  PUMA  \
0       Alabama          1     100100   100
1       Alabama          1     100200   200
2       Alabama          1     100300   300
3       Alabama          1     100400   400
4       Alabama          1     100500   500
...         ...        ...        ...   ...
2064  Wisconsin         55    5502500  2500
2065    Wyoming         56    5600100   100
2066    Wyoming         56    5600200   200
2067    Wyoming         56    5600300   300
2068    Wyoming         56    5600400   400

                                   Counties Within PUMA  uninsured_total  \
0                     Lauderdale County, Colbert County            18517
1                                 Madison County (part)            28109
2                                 Madison County (part)            26568
3                         DeKalb County, Jackson County            21245
4       Marshall County, Cullman County, Winston County            25654
...                                                 ...              ...
2064                                   Sheboygan County            10295
2065  Sweetwater County, Park County, Uinta County, ...            22304
2066      Natrona County, Fremont County, Carbon County            21554
2067  Campbell County, Sheridan County, Goshen Count...            23115
2068                      Laramie County, Albany County            15521

      uninsured_percent  Foodstamp  Age0_18  Age19_25  ...  AsianNonLatino  \
0                  15.3     7754.0    445.0      4358  ...              9
1                  19.0     8364.0   1506.0      4865  ...            570
2                  12.1     6620.0   1147.0      4786  ...            120
3                  20.4     6330.0   6713.0      2582  ...            -
4                  16.0     8155.0   3627.0      5429  ...            332
...                 ...        ...      ...       ...  ...             ...
2064               10.7     3780.0    583.0      2172  ...            541
2065               18.2     2569.0   3311.0      2179  ...            -
2066               18.6     5207.0   3298.0      3254  ...            -
2067               16.7     3057.0   3272.0      3710  ...            155
2068               13.6     1147.0   1939.0      3833  ...            -

     Multiracial_or_Other Disabled FullTime_Worker_in_Family LessThanHS  \
0                    -      3,484                    13,213      3,557
1                    323    3,822                    19,728      5,363
2                    518    2,889                    17,397      5,703
3                    403    2,428                    15,651      7,939
4                    287    3,694                    19,066      7,870
...                   ...      ...                       ...        ...
2064                 140      670                     6,844      1,754
2065                 429    1,393                    20,453      1,830
2066               1,439    2,039                    18,831      3,979
2067                 238    2,572                    19,224      3,259
2068                  89    1,173                    12,975      1,659

     HSDiploma CollegeGrad NoEnglishAdults_in_House EnglishSpeaking Spanish
0      13,685       1,275                     783.0           17665   852.0
1      19,910       2,835                     360.0           27579   491.0
2      18,290       2,574                     672.0           25729   839.0
3      13,059         247                     135.0           20800   446.0
4      17,006         778                    1236.0           24218  1313.0
...        ...         ...                      ...             ...     ...
2064    7,539       1,003                     596.0            9372   220.0
2065   18,816       1,658                     502.0           21822   482.0
2066   15,762       1,813                     202.0           21398   157.0
2067   18,551       1,305                     493.0           22658   302.0
2068   11,555       2,306                     127.0           15462    58.0

[1834 rows x 30 columns]

In [467]:
df.info()
print(df)

<class 'pandas.core.frame.DataFrame'>
Index: 1834 entries, 0 to 2068
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StateName                  1834 non-null   object
 1   StateFIPS                  1834 non-null   int64
 2   PumaState                  1834 non-null   int64
 3   PUMA                       1834 non-null   int64
 4   Counties Within PUMA       1834 non-null   object
 5   uninsured_total            1834 non-null   int64
 6   uninsured_percent          1834 non-null   float64
 7   Foodstamp                  1834 non-null   float64
 8   Age0_18                    1834 non-null   float64
 9   Age19_25                   1834 non-null   int64
 10  Age26_34                   1834 non-null   float64
 11  Age35_54                   1834 non-null   object
 12  Age55_64                   1834 non-null   object
 13  Male                       1834 non-null   object
 14  Female                     1834 non-null   object
 15  Married                    1834 non-null   object
 16  ChildinFamily              1834 non-null   object
 17  Latino                     1834 non-null   object
 18  WhiteNonLatino             1834 non-null   object
 19  BlackNonLatino             1834 non-null   object
 20  AsianNonLatino             1834 non-null   object
 21  Multiracial_or_Other       1834 non-null   object
 22  Disabled                   1834 non-null   object
 23  FullTime_Worker_in_Family  1834 non-null   object
 24  LessThanHS                 1834 non-null   object
 25  HSDiploma                  1834 non-null   object
 26  CollegeGrad                1834 non-null   object
 27  NoEnglishAdults_in_House   1834 non-null   float64
 28  EnglishSpeaking            1834 non-null   int64
 29  Spanish                    1834 non-null   float64
dtypes: float64(6), int64(6), object(18)
memory usage: 444.2+ KB
      StateName  StateFIPS  PumaState  PUMA  \
0       Alabama          1     100100   100
1       Alabama          1     100200   200
2       Alabama          1     100300   300
3       Alabama          1     100400   400
4       Alabama          1     100500   500
...         ...        ...        ...   ...
2064  Wisconsin         55    5502500  2500
2065    Wyoming         56    5600100   100
2066    Wyoming         56    5600200   200
2067    Wyoming         56    5600300   300
2068    Wyoming         56    5600400   400

                                   Counties Within PUMA  uninsured_total  \
0                     Lauderdale County, Colbert County            18517
1                                 Madison County (part)            28109
2                                 Madison County (part)            26568
3                         DeKalb County, Jackson County            21245
4       Marshall County, Cullman County, Winston County            25654
...                                                 ...              ...
2064                                   Sheboygan County            10295
2065  Sweetwater County, Park County, Uinta County, ...            22304
2066      Natrona County, Fremont County, Carbon County            21554
2067  Campbell County, Sheridan County, Goshen Count...            23115
2068                      Laramie County, Albany County            15521

      uninsured_percent  Foodstamp  Age0_18  Age19_25  ...  AsianNonLatino  \
0                  15.3     7754.0    445.0      4358  ...              9
1                  19.0     8364.0   1506.0      4865  ...            570
2                  12.1     6620.0   1147.0      4786  ...            120
3                  20.4     6330.0   6713.0      2582  ...            -
4                  16.0     8155.0   3627.0      5429  ...            332
...                 ...        ...      ...       ...  ...             ...
2064               10.7     3780.0    583.0      2172  ...            541
2065               18.2     2569.0   3311.0      2179  ...            -
2066               18.6     5207.0   3298.0      3254  ...            -
2067               16.7     3057.0   3272.0      3710  ...            155
2068               13.6     1147.0   1939.0      3833  ...            -

     Multiracial_or_Other Disabled FullTime_Worker_in_Family LessThanHS  \
0                    -      3,484                    13,213      3,557
1                    323    3,822                    19,728      5,363
2                    518    2,889                    17,397      5,703
3                    403    2,428                    15,651      7,939
4                    287    3,694                    19,066      7,870
...                   ...      ...                       ...        ...
2064                 140      670                     6,844      1,754
2065                 429    1,393                    20,453      1,830
2066               1,439    2,039                    18,831      3,979
2067                 238    2,572                    19,224      3,259
2068                  89    1,173                    12,975      1,659

     HSDiploma CollegeGrad NoEnglishAdults_in_House EnglishSpeaking Spanish
0      13,685       1,275                     783.0           17665   852.0
1      19,910       2,835                     360.0           27579   491.0
2      18,290       2,574                     672.0           25729   839.0
3      13,059         247                     135.0           20800   446.0
4      17,006         778                    1236.0           24218  1313.0
...        ...         ...                      ...             ...     ...
2064    7,539       1,003                     596.0            9372   220.0
2065   18,816       1,658                     502.0           21822   482.0
2066   15,762       1,813                     202.0           21398   157.0
2067   18,551       1,305                     493.0           22658   302.0
2068   11,555       2,306                     127.0           15462    58.0

[1834 rows x 30 columns]

In [468]:
df.describe()

,StateFIPS,PumaState,PUMA,uninsured_total,uninsured_percent,Foodstamp,Age0_18,Age19_25,Age26_34,NoEnglishAdults_in_House,EnglishSpeaking,Spanish
count,1834.000000,1.834000e+03,1834.000000,1834.000000,1834.000000,1834.000000,1834.000000,1834.000000,1834.000000,1834.000000,1834.000000,1834.000000
mean,26.881679,2.690515e+06,2346.959106,20913.197928,16.261559,5021.521265,2931.963468,3910.552345,4371.673937,2095.210469,18011.526718,2081.599782
std,16.016790,1.601496e+06,2507.490858,10251.781532,6.535281,3640.675056,2405.003087,2193.523575,2202.252103,2747.984346,8746.636421,3246.564307
min,1.000000,1.001000e+05,100.000000,1305.000000,1.500000,47.000000,69.000000,136.000000,35.000000,3.000000,1222.000000,1.000000
25%,12.000000,1.202801e+06,900.000000,13392.000000,11.500000,2133.750000,1259.750000,2323.000000,2791.250000,368.750000,11690.500000,259.500000
50%,26.000000,2.603703e+06,1952.000000,19245.000000,15.800000,4473.000000,2279.000000,3550.000000,4059.000000,1083.000000,16728.000000,797.500000
75%,41.000000,4.100275e+06,3501.000000,26539.250000,20.400000,7120.000000,3824.750000,5067.500000,5483.750000,2761.000000,22754.500000,2422.250000
max,56.000000,5.600400e+06,77777.000000,86343.000000,42.000000,24182.000000,17734.000000,16306.000000,18850.000000,34834.000000,80843.000000,41853.000000

In [484]:
df["StateFIPS"] = df["StateFIPS"].astype(object)
df.dtypes

df["PumaState"] = df["PumaState"].astype(object)
df.dtypes

df["PUMA"] = df["PUMA"].astype(object)
df.dtypes

df["StateName"] = df["StateName"].astype(object)

df["Counties Within PUMA"] = df["Counties Within PUMA"].astype(object)

In [470]:
df

,StateName,StateFIPS,PumaState,PUMA,Counties Within PUMA,uninsured_total,uninsured_percent,Foodstamp,Age0_18,Age19_25,...,AsianNonLatino,Multiracial_or_Other,Disabled,FullTime_Worker_in_Family,LessThanHS,HSDiploma,CollegeGrad,NoEnglishAdults_in_House,EnglishSpeaking,Spanish
0,Alabama,1,100100,100,"Lauderdale County, Colbert County",18517,15.3,7754.0,445.0,4358,...,9,-,"3,484","13,213","3,557","13,685","1,275",783.0,17665,852.0
1,Alabama,1,100200,200,Madison County (part),28109,19.0,8364.0,1506.0,4865,...,570,323,"3,822","19,728","5,363","19,910","2,835",360.0,27579,491.0
2,Alabama,1,100300,300,Madison County (part),26568,12.1,6620.0,1147.0,4786,...,120,518,"2,889","17,397","5,703","18,290","2,574",672.0,25729,839.0
3,Alabama,1,100400,400,"DeKalb County, Jackson County",21245,20.4,6330.0,6713.0,2582,...,-,403,"2,428","15,651","7,939","13,059",247,135.0,20800,446.0
4,Alabama,1,100500,500,"Marshall County, Cullman County, Winston County",25654,16.0,8155.0,3627.0,5429,...,332,287,"3,694","19,066","7,870","17,006",778,1236.0,24218,1313.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2064,Wisconsin,55,5502500,2500,Sheboygan County,10295,10.7,3780.0,583.0,2172,...,541,140,670,"6,844","1,754","7,539","1,003",596.0,9372,220.0
2065,Wyoming,56,5600100,100,"Sweetwater County, Park County, Uinta County, ...",22304,18.2,2569.0,3311.0,2179,...,-,429,"1,393","20,453","1,830","18,816","1,658",502.0,21822,482.0
2066,Wyoming,56,5600200,200,"Natrona County, Fremont County, Carbon County",21554,18.6,5207.0,3298.0,3254,...,-,"1,439","2,039","18,831","3,979","15,762","1,813",202.0,21398,157.0
2067,Wyoming,56,5600300,300,"Campbell County, Sheridan County, Goshen Count...",23115,16.7,3057.0,3272.0,3710,...,155,238,"2,572","19,224","3,259","18,551","1,305",493.0,22658,302.0
2068,Wyoming,56,5600400,400,"Laramie County, Albany County",15521,13.6,1147.0,1939.0,3833,...,-,89,"1,173","12,975","1,659","11,555","2,306",127.0,15462,58.0

In [471]:
df = df.replace(r"[\,\**\-\.0\'  ']", '', regex=True)
df

C:\Users\menmt\AppData\Local\Temp\ipykernel_2548\4066847586.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"[\,\**\-\.0\'  ']", '', regex=True)

,StateName,StateFIPS,PumaState,PUMA,Counties Within PUMA,uninsured_total,uninsured_percent,Foodstamp,Age0_18,Age19_25,...,AsianNonLatino,Multiracial_or_Other,Disabled,FullTime_Worker_in_Family,LessThanHS,HSDiploma,CollegeGrad,NoEnglishAdults_in_House,EnglishSpeaking,Spanish
0,Alabama,1,100100,100,LauderdaleCountyColbertCounty,18517,15.3,7754.0,445.0,4358,...,9,,3484,13213,3557,13685,1275,783.0,17665,852.0
1,Alabama,1,100200,200,MadisonCounty(part),28109,19.0,8364.0,1506.0,4865,...,57,323,3822,19728,5363,1991,2835,360.0,27579,491.0
2,Alabama,1,100300,300,MadisonCounty(part),26568,12.1,6620.0,1147.0,4786,...,12,518,2889,17397,573,1829,2574,672.0,25729,839.0
3,Alabama,1,100400,400,DeKalbCountyJacksonCounty,21245,20.4,6330.0,6713.0,2582,...,,43,2428,15651,7939,1359,247,135.0,20800,446.0
4,Alabama,1,100500,500,MarshallCountyCullmanCountyWinstonCounty,25654,16.0,8155.0,3627.0,5429,...,332,287,3694,1966,787,176,778,1236.0,24218,1313.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2064,Wisconsin,55,5502500,2500,SheboyganCounty,10295,10.7,3780.0,583.0,2172,...,541,14,67,6844,1754,7539,13,596.0,9372,220.0
2065,Wyoming,56,5600100,100,SweetwaterCountyParkCountyUintaCountyTetonCoun...,22304,18.2,2569.0,3311.0,2179,...,,429,1393,2453,183,18816,1658,502.0,21822,482.0
2066,Wyoming,56,5600200,200,NatronaCountyFremontCountyCarbonCounty,21554,18.6,5207.0,3298.0,3254,...,,1439,239,18831,3979,15762,1813,202.0,21398,157.0
2067,Wyoming,56,5600300,300,CampbellCountySheridanCountyGoshenCountyConver...,23115,16.7,3057.0,3272.0,3710,...,155,238,2572,19224,3259,18551,135,493.0,22658,302.0
2068,Wyoming,56,5600400,400,LaramieCountyAlbanyCounty,15521,13.6,1147.0,1939.0,3833,...,,89,1173,12975,1659,11555,236,127.0,15462,58.0

In [511]:
df["Male"] = df["Male"].astype(int)
df.dtypes

df["Age0_18"] = df["Age0_18"].astype(int)
df.dtypes

df["Foodstamp"] = df["Foodstamp"].astype(int)
df.dtypes

df["Age26_34"] = df["Age26_34"].astype(int)

df["Age35_54"] = df["Age35_54"].astype(int)

df["Age55_64"] = df["Age55_64"].astype(int)
df.dtypes

df["Female"] = df["Female"].astype(int)
df.dtypes

df["Married"] = df["Married"].astype(int)
df.dtypes

df["ChildinFamily"] = df["ChildinFamily"].astype(int)

In [508]:
df.dtypes

StateName                     object
StateFIPS                     object
PumaState                     object
PUMA                          object
Counties Within PUMA          object
uninsured_total                int64
uninsured_percent            float64
Foodstamp                      int64
Age0_18                        int64
Age19_25                       int64
Age26_34                       int64
Age35_54                       int64
Age55_64                       int64
Male                           int64
Female                         int64
Married                        int64
ChildinFamily                  int64
Latino                        object
WhiteNonLatino                object
BlackNonLatino                object
AsianNonLatino                object
Multiracial_or_Other          object
Disabled                      object
FullTime_Worker_in_Family     object
LessThanHS                    object
HSDiploma                     object
CollegeGrad                   object
NoEnglishAdults_in_House     float64
EnglishSpeaking                int64
Spanish                      float64
dtype: object

In [ ]:
df['StateFIPS'] = df['StateFIPS'].astype(object)
df.dtypes

df["PumaState"] = df["PumaState"].astype(object)
df.dtypes

df["PUMA"] = df["PUMA"].astype(object)
df.dtypes

df["StateName"] = df["StateName"].astype(object)

df["Counties Within PUMA"] = df["Counties Within PUMA"].astype(object)

KeyError: 'StateFIPS'

In [ ]:
df = df.astype({'Age35_54':  int,'Age55_64': int, 'Male': int, 'Female': int, 'Married': int, 'ChildinFamily': int, 'WhiteNonLatino': int, 'BlackNonLatino': int, 'AsianNonLatino': int, 'Multiracial_or_Other': int, 'Disabled': int, 'FullTime_Worker_in_Family': int, 'LessThanHS': int, 'HSDiploma': int, 'CollegeGrad': int, 'NoEnglishAdults_in_House': int, 'EnglishSpeaking': int, 'Spanish': int}) 
print("\nConverted:\n")
print(df.dtypes)

KeyError: 'Only the Series name can be used for the key in Series dtype mappings.'

In [ ]:
df.sample

<bound method NDFrame.sample of       StateName  StateFIPS  PumaState  PUMA  \
0       Alabama          1     100100   100
1       Alabama          1     100200   200
2       Alabama          1     100300   300
3       Alabama          1     100400   400
4       Alabama          1     100500   500
...         ...        ...        ...   ...
2064  Wisconsin         55    5502500  2500
2065    Wyoming         56    5600100   100
2066    Wyoming         56    5600200   200
2067    Wyoming         56    5600300   300
2068    Wyoming         56    5600400   400

                                   Counties Within PUMA  uninsured_total  \
0                         LauderdaleCountyColbertCounty            18517
1                                   MadisonCounty(part)            28109
2                                   MadisonCounty(part)            26568
3                             DeKalbCountyJacksonCounty            21245
4              MarshallCountyCullmanCountyWinstonCounty            25654
...                                                 ...              ...
2064                                    SheboyganCounty            10295
2065  SweetwaterCountyParkCountyUintaCountyTetonCoun...            22304
2066             NatronaCountyFremontCountyCarbonCounty            21554
2067  CampbellCountySheridanCountyGoshenCountyConver...            23115
2068                          LaramieCountyAlbanyCounty            15521

      uninsured_percent  Foodstamp  Age0_18  Age19_25  ...  AsianNonLatino  \
0                  15.3     7754.0    445.0      4358  ...               9
1                  19.0     8364.0   1506.0      4865  ...              57
2                  12.1     6620.0   1147.0      4786  ...              12
3                  20.4     6330.0   6713.0      2582  ...
4                  16.0     8155.0   3627.0      5429  ...             332
...                 ...        ...      ...       ...  ...             ...
2064               10.7     3780.0    583.0      2172  ...             541
2065               18.2     2569.0   3311.0      2179  ...
2066               18.6     5207.0   3298.0      3254  ...
2067               16.7     3057.0   3272.0      3710  ...             155
2068               13.6     1147.0   1939.0      3833  ...

     Multiracial_or_Other Disabled FullTime_Worker_in_Family LessThanHS  \
0                             3484                     13213       3557
1                     323     3822                     19728       5363
2                     518     2889                     17397        573
3                      43     2428                     15651       7939
4                     287     3694                      1966        787
...                   ...      ...                       ...        ...
2064                   14       67                      6844       1754
2065                  429     1393                      2453        183
2066                 1439      239                     18831       3979
2067                  238     2572                     19224       3259
2068                   89     1173                     12975       1659

     HSDiploma CollegeGrad NoEnglishAdults_in_House EnglishSpeaking Spanish
0        13685        1275                    783.0           17665   852.0
1         1991        2835                    360.0           27579   491.0
2         1829        2574                    672.0           25729   839.0
3         1359         247                    135.0           20800   446.0
4          176         778                   1236.0           24218  1313.0
...        ...         ...                      ...             ...     ...
2064      7539          13                    596.0            9372   220.0
2065     18816        1658                    502.0           21822   482.0
2066     15762        1813                    202.0           21398   157.0
2067     18551         135                    493.0           22658   302.0
2068     11555         236                    127.0           15462    58.0

[1834 rows x 30 columns]>

In [ ]:
 #, 'Age55_64': 'int', 'Male': int, 'Female': int, 'Married': int, 'ChildinFamily': int, 'Latino': int, 'WhiteNonLatino': int, 'BlackNonLatino': int, 'AsianNonLatino': int, 'Multiracial_or_Other': int, 'Disabled': int, 'FullTime_Worker_in_Family': int, 'LessThanHS': int, 'HSDiploma': int, 'CollegeGrad': int, 'NoEnglishAdults_in_House': int, 'EnglishSpeaking': int, 'Spanish': int, 'OtherLanguage': int})

In [ ]:
df.dtypes

dtype('int64')

SQL

VISUALIZATIONS